### ISSUE TITLE
Handle more wav encoding

### ISSUE THREAD

**Issue by ybayle** [lacimarsik/harmony-analyser#17]
The program crashes for the feature extraction of some wav files. Here is a list of errors:
- `ERROR: Only 16-bit signed little-endian PCM files supported` for `ABBA - Dancing Queen - 7300 - nbv-bv-ld.wav`
- Cannot compute the whole set of features for `Cabaret - Maybe This Time - 8711 - nbv-ld.wav`

**Comment by lacimarsik** [comment]
This should now be resolved in master via https://github.com/lacimarsik/harmony-analyser/pull/19
