### ISSUE TITLE
Version 1.2 fails to run

### ISSUE THREAD

**Issue by alexh8555** [lacimarsik/harmony-analyser#21]
I was trying to use harmony-analyser however I encounter some problems.

Ver1.1 runs without problem but when I try to run ver1.2 by 
`java -jar target/ha-executable-1.2-beta.jar`
it says
`Error: Could not find or load main class org.harmony_analyser.application.HarmonyAnalyser
`
in terminal.

I'm using ubuntu 16.04 and I think I've installed everything correctly since ver1.1 works. I would like to try out the TPS Distance function in ver1.2.
Am I doing anything wrong?

**Comment by lacimarsik** [comment]
Apologies about this issue @alexh8555 !

I can replicate this for v 1.2. Something must have gone wrong with the packaging.

While I debug this issue (I'd need at least the weekend), can you please use ha-script in the meantime? That was tested to work well. Using `-p chord_analyser:tps_distance -s .wav` should analyse all .wav files in the current folder and output TPS distances.

**Comment by lacimarsik** [comment]
Alternatively, I've used the v 1.2 many times running from the source, so if you need it fast, you can go ahead and clone the repository. For this to run (I recommend in IntelliJ IDEA), there is 1 more [development requirement](https://github.com/lacimarsik/harmony-analyser#development)

**Comment by alexh8555** [comment]
Thank you for your prompt reply!
I am able to get the TPS distance after generate labels, tones and keys ha-script now!
I'm not familiar with JAVA so I guess I'll wait for your v 1.2 jar.
Thanks for helping me out.
